from fastapi import APIRouter, Request, UploadFile, File, Form, Depends
from fastapi.responses import HTMLResponse, JSONResponse
import logging
from pathlib import Path
from engine.llm import LLMAdapter
from core.parser import FileParser

router = APIRouter(prefix="/ai", tags=["AI Studio"])
logger = logging.getLogger(__name__)

@router.get("/studio", response_class=HTMLResponse)
async def ai_studio_page(request: Request):
    """Render the AI Studio UI."""
    return request.app.state.templates.TemplateResponse(
        "ai_studio.html",
        {"request": request}
    )

@router.post("/generate")
async def generate_tests(
    file: UploadFile = File(...),
    provider: str = Form(...),
    api_key: str = Form(...)
):
    """Generate tests from an uploaded file using the specified LLM."""
    try:
        content = await file.read()
        
        # 1. Parse the uploaded file into raw text steps
        raw_steps = FileParser.parse_file(file.filename, content)
        
        # 2. Use the LLM adapter to generate instructions
        adapter = LLMAdapter(provider=provider, api_key=api_key)
        instructions = adapter.generate_test_instructions(raw_steps)
        
        return JSONResponse(content={"status": "success", "instructions": instructions})
        
    except Exception as e:
        logger.error(f"Failed to generate tests: {e}")
        return JSONResponse(status_code=400, content={"status": "error", "message": str(e)})

from pydantic import BaseModel
from typing import List, Dict, Any
from core import database

class AIImportRequest(BaseModel):
    name: str
    url: str
    instructions: List[Dict[str, Any]]

@router.post("/import")
async def import_ai_test(request: Request, data: AIImportRequest):
    """Create a new test from AI generated instructions."""
    db_path = request.app.state.db_path
    try:
        # Create the test
        test = await database.create_test(
            db_path,
            name=data.name,
            url=data.url,
            mode="recorded",
            description="Generated by AI Studio"
        )
        
        # Create the steps
        for i, step_data in enumerate(data.instructions):
            sequence = i + 1
            action = step_data.get("action", "assert_text")
            selector = step_data.get("selector", "")
            value = step_data.get("value", "")
            description = step_data.get("description", "")
            
            # Basic validation
            if not selector and action != "navigate":
                selector = "element"
                
            await database.create_step(
                db_path,
                test_id=test.id,
                sequence=sequence,
                action=action,
                selector=selector,
                value=value,
                description=description,
                is_sensitive=False
            )
            
        return {"status": "success", "test_id": test.id}
    except Exception as e:
        logger.error(f"Failed to import AI test: {e}")
        return JSONResponse(status_code=500, content={"status": "error", "message": str(e)})

import uuid
import asyncio
import os
from browser_use import Agent
from browser_use.agent.views import AgentHistory
from langchain_openai import ChatOpenAI

# Patch ChatOpenAI to provide a 'provider' attribute which browser-use 0.12+ expects
if not hasattr(ChatOpenAI, 'provider'):
    ChatOpenAI.provider = property(lambda self: 'openai')

# In-memory job tracker
record_jobs = {}

@router.post("/record-test")
async def start_record_test(
    request: Request,
    file: UploadFile = File(...),
    test_name: str = Form(...),
    test_url: str = Form(...),
    provider: str = Form(...),
    api_key: str = Form(...)
):
    """Start background autonomous recording."""
    content = await file.read()
    raw_steps = FileParser.parse_file(file.filename, content)
    
    job_id = str(uuid.uuid4())
    record_jobs[job_id] = {"status": "running", "test_id": None, "error": None}
    
    db_path = request.app.state.db_path
    config = request.app.state.config
    
    from core.config import resolve_password
    try:
        password = resolve_password(config)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Failed to resolve password: {str(e)}"})
    
    # Launch background task in a dedicated thread with proper Windows event loop policy
    def _run_in_thread():
        import sys
        import asyncio
        if sys.platform == 'win32':
            asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        asyncio.run(_run_smart_recorder(
            job_id=job_id,
            name=test_name,
            url=test_url,
            api_key=api_key,
            raw_steps_str=raw_steps,
            db_path=db_path,
            config=config,
            password=password
        ))
        
    import threading
    threading.Thread(target=_run_in_thread).start()
    
    return {"status": "success", "job_id": job_id}

@router.get("/job/{job_id}")
async def get_job_status(job_id: str):
    """Poll job status."""
    if job_id not in record_jobs:
        return JSONResponse(status_code=404, content={"error": "Job not found"})
    return record_jobs[job_id]

async def _run_smart_recorder(job_id: str, name: str, url: str, api_key: str, raw_steps_str: str, db_path: Path, config, password: str):
    try:
        os.environ["OPENAI_API_KEY"] = api_key
        llm = ChatOpenAI(model="gpt-4o")
        
        task_str = f"Go to {url} and perform the following sequence:\n"
        task_str += "CRITICAL RULES:\n"
        task_str += "1. NEVER search Google or navigate away from the target URL. If a page is blank, wait or refresh.\n"
        if password and config.fusion_user:
            task_str += f"2. If presented with a login screen, use Username: '{config.fusion_user}' and Password: '{password}'.\n"
        task_str += "\nSTEPS:\n"
        task_str += raw_steps_str
            
        agent = Agent(task=task_str, llm=llm)
        history_list = await agent.run()
        
        # Parse history into steps
        db_steps = []
        seq = 1
        
        # Initial navigation step
        db_steps.append({
            "sequence": seq,
            "action": "navigate",
            "selector": "element",
            "value": url,
            "description": f"Navigate to {url}"
        })
        seq += 1
        
        for item in history_list.history:
            if not item.model_output or not item.model_output.action:
                continue
                
            interacted_els = item.state.interacted_element if hasattr(item.state, 'interacted_element') else []
            if not interacted_els:
                interacted_els = [None] * len(item.model_output.action)
                
            for action_obj, el in zip(item.model_output.action, interacted_els):
                action_dict = action_obj.model_dump(exclude_none=True)
                action_name = list(action_dict.keys())[0] if action_dict else ""
                
                db_action = "click"
                selector = "element"
                value = ""
                
                if el and el.xpath:
                    selector = f"xpath={el.xpath}"
                    
                if action_name == "click_element":
                    db_action = "click"
                elif action_name == "input_text":
                    db_action = "fill"
                    value = action_dict[action_name].get("text", "")
                elif action_name == "go_to_url":
                    db_action = "navigate"
                    value = action_dict[action_name].get("url", "")
                elif action_name == "scroll_down" or action_name == "scroll_up":
                    continue # Ignore scrolling
                else:
                    # fallback
                    db_action = "assert_text"
                    
                desc = f"{db_action} on {el.tag_name if el else 'page'}"
                
                db_steps.append({
                    "sequence": seq,
                    "action": db_action,
                    "selector": selector,
                    "value": value,
                    "description": desc
                })
                seq += 1
                
        # Save to DB
        test = await database.create_test(db_path, name=name, url=url, mode="recorded", description="Recorded autonomously")
        for s in db_steps:
            await database.create_step(
                db_path, test.id, s["sequence"], s["action"], 
                s["selector"], s["value"], s["description"], False
            )
            
        record_jobs[job_id]["status"] = "success"
        record_jobs[job_id]["test_id"] = test.id
        
    except Exception as e:
        logger.error(f"Background recording failed: {e}")
        record_jobs[job_id]["status"] = "error"
        record_jobs[job_id]["error"] = str(e)
